INSERT INTO CUSTOMER(USERNAME,PASSWORD,EMAIL) VALUES 
('JAFFA', 'DOGS29', 'JAKE@GMAIL.COM'),
('GEORGEEOO', '20GEORGE20', 'GEORGE@GMAIL.COM'),
('MAT', 'MAT2020', 'MAT@HOTMAIL.CO.UK');

INSERT INTO ITEM (NAME,DESCRIPTION,PRICE) VALUES
('Escape', 'Pack of 40 cards', '20.00'),
('Maths', 'Pack of 40 cards', '20.00'),
('Super Sign', 'Pack of 40 cards', '20.00');

INSERT INTO ORDER_TABLE (CUSTOMER_ID) VALUES
(1),
(2),
(3);

INSERT INTO LINE_ITEM (ORDERTABLE_ID,ITEM_ID,QUANTITY) VALUES
(1,3,2),
(1,1,3),
(2,1,3),
(2,2,1),
(3,1,2);